### ISSUE TITLE
Serializable SnapshotAggregateRoot

### ISSUE THREAD

**Issue by managerger** [sachabarber/SachaBarber.CQRS.Demo#2]
I've faced with a problem, when I can't serialize SnapshotAggregateRoot. Of course, I can get around the issue by writing SurrogateSerializer, but it seems to be a common task to serialize aggregate when you have a deal with snapshoting (I try to implement memento pattern). So, it would be great to mark SnapshotAggregateRoot and AggregateRoot with [Serializable] attribute.

**Comment by sachabarber** [comment]
You should probably post this on the core CQRS framework that I used, as its really a question for that repo

**Comment by managerger** [comment]
Yeah, you r totally right. You repo was the first in Google search and I didn't pay attention. My bad

**Comment by sachabarber** [comment]
No problem
